; Configuration specific to GPURowhammer itself. We will only explain new things
[rh_config]
num_agg = 24
step = 256
row_step = 4
num_rows = 31000
it = 23000;
n = 8;
k = 3;
delay = 55;
period = 1;

; Repeat the attack `repeat` times when hammering
repeat = 50; 

; This is the memory size our gpubreach program will use too in Step 1.
mem_size = 49392123904; 


; Configuration specific to trigger the bit-flip
[flip_config]

; Whether the aggressor is on the left or right side or the vic_row
left = true

; Victim row you want to hammer
vic_row = 30016

; Critical Aggressor that triggers it
; Depending on `left`, the aggressors are chosen like below.
;                     ← Left   Right →             ;
; A       ...       crit_agg V crit_agg       ...       A ;
crit_agg = 30014

; aggressor data pattern
agg_pat = 0xAA

; Row set file in $HAMMER_ROOT/results/row_sets
row_set_file = ROW_SET_A.txt