; Configuration specific to GPURowhammer itself
[rh_config]
num_agg = 24
step = 256
row_step = 4
num_rows = 31000
it = 23000;
n = 8;
k = 3;
delay = 55;
period = 1;
repeat = 50;


; Configuration specific to trigger the bit-flip
[flip_config]
left = true
vic_row = 30016
crit_agg = 30014
agg_pat = 0xAA
row_set_file = ROW_SET_A.txt